spring:
  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      data-locations: sql/data.sql
      schema-locations: sql/schema.sql
      mode: embedded

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true