quiz:
  required-score: 3

application:
  title: Quiz App
  version: 1.0.0
  language-tag: ru-RU

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
    use-code-as-default-message: true
