spring:
  datasource:
    url: jdbc:h2:mem:testdb

  sql:
    init:
      mode: embedded
      data-locations: sql/data.sql
      schema-locations: sql/schema.sql

  #todo: ???? ??? ??? ??? ????
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true